version: '3.8'

services:
    # Backend API
    smart-brain-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        environment:
            POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
            # POSTGRES_USER: sally
            # POSTGRES_PASSWORD: secret
            # POSTGRES_DB: smart-brain-docker
            # POSTGRES_HOST: postgres # the name of the docker service, not 127.0.0.1
        links:
            - postgres
        ports: 
            - "3000:3000"
        volumes:
                - ./:/usr/src/smart-brain-api 
    
    # Postgres
    postgres:
        environment:
            # POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker ,
            # POSTGRES_HOST_AUTH_METHOD: "trust"
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres # the name of the docker service, not 127.0.0.1
        build: ./postgres
        ports:
            - "5432:5432"